version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mo
      - MYSQL_DATABASE=test
      - MYSQL_USER=mo
      - MYSQL_PASSWORD=mo
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: always