version: '3'

services:
  db:
    image: postgres:11.5-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER:  'mo'
      POSTGRES_PASSWORD: 'mo'
      POSTGRES_DB: 'todo'
    volumes:
      - ./schema/create_db_postgres.sql:/docker-entrypoint-initdb.d/init.sql